version: '3.8'

services:
  redis:
    image: redis:7.2-alpine  # конкретная версия
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/etc/redis/  # кастомный конфиг
    command: redis-server --maxclients 15000
    environment:
      - REDIS_PASSWORD=bigboxpass  # опционально
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3